all:
	g++ estacionamento.c --std=c++11 -g -o estacionamento
	g++ browser.c --std=c++11 -g -o browser
	g++ tarefas.c --std=c++11 -g -o tarefas

clean:
	rm estacionamento browser tarefas

debug:
	nemiver ./tarefas
