all:
	g++ salao.cpp --std=c++11 -g -o salao
	g++ salao2.cpp --std=c++11 -g -o salao2
	g++ banco.cpp --std=c++11 -g -o banco
	g++ banco_preferencial.cpp --std=c++11 -g -o banco_preferencial

clean:
	rm salao salao2 banco banco_preferencial *~ -rf
